In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

Init Plugin
Init Graph Optimizer
Init Kernel


In [2]:
dataset = pd.read_csv('/Users/zunairaasif/Downloads/train.csv')

In [3]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

In [4]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
print(y) 


[1 0 1 ... 7 6 9]


Encoding Catergorical Data


In [6]:
y = tf.one_hot(y, 10)

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-09-01 07:18:41.809133: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-09-01 07:18:41.810527: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [7]:
print(y)

tf.Tensor(
[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]], shape=(42000, 10), dtype=float32)


Feature Scaling

In [8]:
from sklearn.preprocessing import MinMaxScaler

Ns = MinMaxScaler()
X = Ns.fit_transform(X)


Constructing ANN

In [19]:
ann = tf.keras.models.Sequential()

In [20]:
ann.add(tf.keras.layers.Dense(units=50, activation='relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units=50, activation='sigmoid'))

In [23]:
ann.add(tf.keras.layers.Dense(units=10 , activation= 'sigmoid'))

In [24]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [30]:
ann.fit(X, y, batch_size = 32, epochs = 5)

Epoch 1/5
1313/1313 [==============================] - 10s 8ms/step - loss: 0.0357 - accuracy: 0.9884
Epoch 2/5
1313/1313 [==============================] - 10s 7ms/step - loss: 0.0317 - accuracy: 0.9897
Epoch 3/5
1313/1313 [==============================] - 10s 8ms/step - loss: 0.0266 - accuracy: 0.9919
Epoch 4/5
1313/1313 [==============================] - 10s 8ms/step - loss: 0.0249 - accuracy: 0.9920
Epoch 5/5
1313/1313 [==============================] - 10s 8ms/step - loss: 0.0237 - accuracy: 0.9922


In [31]:
Data_test = pd.read_csv('/Users/zunairaasif/Desktop/Mnist_Model_tf/test.csv')

In [32]:
Data_test = Ns.transform(Data_test)

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
  warnings.warn(


In [33]:
y_pred = ann.predict(Data_test)



results = np.argmax(y_pred, axis=1)
results.shape , results

((28000,), array([2, 0, 9, ..., 3, 9, 2]))

In [34]:
image_id = pd.Series(range(1,28001),name='ImageId')
y_preds = pd.Series(results,name = 'Label')
pred = pd.concat([image_id,y_preds],axis=1)
pred.to_csv('submission.csv',index=False)