In [48]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


In [49]:
data = pd.read_csv('/Users/zunairaasif/Downloads/train.csv')


In [50]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [51]:
data = np.array(data)
m, n = data.shape
np.random .shuffle(data)

data_dev = data[0:1000].T
X_dev = data_dev[1:n]
Y_dev = data_dev[0]

data_train = data[1000:m].T
X_train = data_train[1:n]
Y_train = data_train[0]

Ns = MinMaxScaler()
X_train = Ns.fit_transform(X_train)


In [52]:
def init_params():
    W1 = np.random.randn(100,784) 
    b1 = np.random.randn(100,1) 
    
    W2 = np.random.randn(10, 100) 
    b2 = np.random.randn(10,1)
    return W1, b1, W2, b2


In [53]:
def Sigmoid(Z):
    return  1.0/(1.0+np.exp(-Z))
    

In [54]:
def deriv_sigmoid(Z):
    return Sigmoid(Z)*(1-Sigmoid(Z))

In [55]:
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = Sigmoid(Z1)
    
    Z2 = W2.dot(A1) + b2
    A2 = Sigmoid(Z2)
    
    return Z1, A1, Z2, A2
    
    

In [56]:
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

In [57]:
def back_prop(W1,  W2, Z1, Z2, A1, A2, X, Y):
    m = Y.size
    one_hot_Y = one_hot(Y)
    
    dZ2 = 2*(A2 - one_hot_Y)
    dW2 = 1/m*dZ2.dot(A1.T)
    db2 = 1/m*np.sum(dZ2,1)
    
    dZ1 = W2.T.dot(dZ2)*deriv_sigmoid(Z1)
    dW1 = 1/m*dZ1.dot(X.T)
    db1 = 1/m*np.sum(dZ1,1)
    
    return  dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha*dW1
    
    W2 = W2 - alpha*dW2
    
    b1 = b1 - alpha*np.reshape(db1, (100,1))
    
    b2 = b2 - alpha*np.reshape(db2, (10,1))
    
    return W1, b1, W2, b2

In [58]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size


In [59]:
def gradient_descent(X, Y, iterations, alpha):
    
    W1, b1, W2, b2 = init_params()
    
    for i in range(iterations):  
        
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
    
        dW1, db1, dW2, db2 = back_prop(W1,  W2, Z1, Z2, A1, A2, X, Y)
        
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2
    
    

In [60]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 1000, 3)

Iteration:  0
[9 9 9 ... 9 9 9] [4 8 7 ... 0 9 1]
0.10407317073170731
Iteration:  10
[4 2 7 ... 6 9 1] [4 8 7 ... 0 9 1]
0.5583658536585366
Iteration:  20
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.6877073170731707
Iteration:  30
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.7456829268292683
Iteration:  40
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.7777804878048781
Iteration:  50
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.7984146341463415
Iteration:  60
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.813
Iteration:  70
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.8242195121951219
Iteration:  80
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.8335853658536585
Iteration:  90
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.8420731707317073
Iteration:  100
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.8485853658536585
Iteration:  110
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.8545609756097561
Iteration:  120
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.860780487804878
Iteration:  130
[4 2 7 ... 0 9 1] [4 8 7 ... 0 9 1]
0.8654634146341463
Iteration:  140
[4 2 7 ... 0 9

KeyboardInterrupt: 